application:
   version: v1.0.0
   title: oauth2-example
server:
   port: 8080
spring:
   thymeleaf:
      cache: false
      mode: HTML
      prefix: file:src/main/resources/templates/
   devtools:
      livereload:
         enabled: true
      restart:
         enabled: true
   security:
      oauth2:
         client:
            registration:
               google:
                  client-id: INSERT_YOUR_ID
                  client-secret: INSERT_YOUR_SECRET
custom:
   oauth2:
      kakao:
         client-id: INSERT_YOUR_ID
         client-secret: INSERT_YOUR_SECRET
      naver:
         client-id: INSERT_YOUR_SECRET
         client-secret: INSERT_YOUR_SECRET