application:
   version: v1.0.0
   title: oauth2-example
server:
   port: 8080
spring:
   thymeleaf:
      cache: false
      mode: HTML
   devtools:
      livereload:
       enabled: true
      restart:
          enabled: true
custom:
   oauth2:
      kakao:
         client-id: INSERT_YOUR_ID
         client-secret: INSERT_YOUR_SECRET
